services:
  milten-app:
    image: lester-app
    container_name: lester-app
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8081:80
      - 2224:22
    volumes:
      - /home/andrey/ansible-files/general-files/authorized_keys:/root/.ssh/authorized_keys
      - /home/andrey/ansible-files/general-files/entrypoint.sh:/root/entrypoint.sh
      - /home/andrey/ansible-files/general-files/sshd.config:/etc/ssh/sshd.config
    entrypoint: ["/root/entrypoint.sh"]
