services:
  gorn-app:
    image: gorn-app
    build:
      context: .
      dockerfile: dockerfile
    container_name: gorn-app
    ports:
      - 2224:22
      - 54321:5432
    volumes:
      - /home/andrey/ansible-files/general-files/sshd_config:/etc/ssh/sshd_config
      - /home/andrey/ansible-files/general-files/authorized_keys:/root/.ssh/authorized_keys
      - /home/andrey/ansible-files/general-files/entrypoint.sh:/entrypoint.sh
    entrypoint: ["./entrypoint.sh"]
