---
- hosts: webservers
#  become: true
  tasks:

  - name: "update apt packages"
    apt:
      update_cache: true
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: "install apache2 package"
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: "start apache2 service"
    ansible.builtin.sysvinit:
      name: apache2
      state: started
      enabled: true
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: "add php support for apache2"
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: "update apt packages for centos"
    become: true
    dnf:
      update_cache: true
    when: ansible_distribution in ["CentOS"]

  - name: "install apache2 for centos"
    become: true
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution in ["CentOS"]

  - name: "install php for centos"
    become: true
    dnf:
      name: php
      state: latest
    when: ansible_distribution in ["CentOS"]

  - name: "start apache2 service for centos"
    become: true
    service:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution in ["CentOS"]

  - name: "enable 80 port for centos"
    become: true
    firewalld:
      port: "80/tcp"
      state: "enabled"
    when: ansible_distribution in ["CentOS"]

...
