---
- hosts: webservers
#  become: true
  tasks:

  - name: "update apt packages"
    apt:
      update_cache: true

  - name: "install apache2 package"
    apt:
      name: apache2
      state: latest

  - name: "start apache2 service"
    ansible.builtin.sysvinit:
      name: apache2
      state: started
      enabled: true

  - name: "add php support for apache2"
    apt:
      name: libapache2-mod-php
      state: latest

...
