---

- hosts: webservers
#  become: true
  tasks:

  - name: "stop apache2 service"
    ansible.builtin.sysvinit:
      name: "{{ apache_package }}"
      state: stopped
      enabled: false
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - name: "remove apache2 and php packages"
    apt:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - name: "stop apache2 service for Centos"
    become: true
    service:
      name: "{{ apache_package }}"
      state: stopped
      enabled: false
    when: ansible_distribution in ['CentOS']

  - name: "remove apache2 package for CentOS"
    become: true
    dnf:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
    when: ansible_distribution in ['CentOS']

...
